language: node_js

node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - npm install

# Scripts to be run such as tests
before_script:
  - npm run test

script:
  - docker --version
  - docker build -t udacity-books-api .
  - docker tag udacity-books-api dcollioni/udacity-books-api:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dcollioni/udacity-books-api
